name: Update Snake

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/snake.svg
            assets/snake-dark.svg?palette=github-dark

      - name: Commit snake SVGs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: daily snake'
          file_pattern: 'assets/snake.svg assets/snake-dark.svg'
